# Site settings
title: Let's HOON!
header-img: img/home-bg.png
email: yl.hoony@gmail.com
copyright_name: ylhoony
description: > # this means to ignore newlines until "baseurl:"
  Tiny World, Big Think
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ylhoony
learn_profile: ylhoony
email_username: yl.hoony@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
